template: |
  ## Release Notes

  $CHANGES

exclude-contributors:
  - 'dependabot'
  - 'dependabot[bot]'
  - 'github-actions[bot]'
change-template: '- $TITLE - [#$NUMBER]($URL) by @$AUTHOR'
categories:
  - title: 💎 Features & Enhancements
    labels:
      - 'area: enhancement :wrench:'
      - 'area: feature request :bulb:'
  - title: 🐞 Bug Fixes
    labels:
      - 'area: bug :bug:'
  - title: 🖥️ Frontend
    labels:
      - 'client: angular'
      - 'client: react'
      - 'client: vue'
  - title: 🍃 Spring Boot
    labels:
      - 'server: spring boot'
  - title: 🔒 Authentication/Security
    labels:
      - 'theme: security'
  - title: 🪶 Maven
    labels:
      - 'theme: maven'
  - title: 🐘 Gradle
    labels:
      - 'theme: gradle'
  - title: 📝 Documentation
    label: 'area: documentation:books:'
  - title: 📦 Dependency updates
    label: 'theme: dependencies'
  - title: 💩 Spam/Invalid
    labels:
      - 'area: spam'
      - 'area: invalid'
