name: Release Drafter
on:
  push:
Zz    branches:
      - main

jobs:
  update_release_draft:
    if: github.repository == 'pascalgrimaud/jhapp-automated-release'
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "main"
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
